name: ART Fibers Pull Request
on: [ pull_request ]
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [macos-11, ubuntu-latest, windows-latest ]
        jdk: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build build-native-executable --max-workers 8 --parallel -PgraalWindowsVisualStudioVars="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
